version: '3.9'

services:
  postgres-desafio-crud:
    image: postgres:15
    container_name: postgres_crud_desafio
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: deal_crud
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: